name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cryo_db:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: r-lib/actions/setup-r@v2
    
    - name: install gdal
      run: |
         sudo apt-get update
         sudo apt-get install gdal-bin libgdal-dev proj-bin libproj-dev proj-data
    
    - name: Install terra package
      run: R -e 'install.packages("terra")'
    
    - name: Install packages
      run: |
        R -e 'install.packages("sf")'
        R -e 'install.packages("pbapply")'
        R -e 'install.packages("tidyr")'
        R -e 'install.packages("readr")'
        R -e 'install.packages("dplyr")'
        R -e 'install.packages("purrr")'
    
    - name: fetch cryo data R script
      working-directory: cryo_db
      run: Rscript fetch_cryo_data.R
      



