name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  fetch:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - run: RScript cryo_db/fetch-cryo_data.R


