name: Fetch Cryo Data

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  cryo_db:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # - uses: r-lib/actions/setup-r@v2
    # 
    # - name: Install system dependencies for (spatial) R packages
    #   run: |
    #      sudo apt-get update
    #      sudo apt-get install gdal-bin libgdal-dev proj-bin libproj-dev proj-data geos-bin libgeos-dev sqlite3 libsqlite3-dev libudunits2-0 libudunits2-dev
    # 
    # - name: Install terra R package
    #   run: R -e 'install.packages("terra")'
    # 
    # - name: Install sf R packages
    #   run: R -e 'install.packages("sf")'
    #   
    # - name: Install non-spataial R packages
    #   run: |
    #     R -e 'install.packages("pbapply")'
    #     R -e 'install.packages("tidyr")'
    #     R -e 'install.packages("readr")'
    #     R -e 'install.packages("dplyr")'
    #     R -e 'install.packages("purrr")'
    # 
    # - name: Run cryo data R script
    #   working-directory: cryo_db
    #   run: Rscript fetch_cryo_data.R

    - name: Commit and push new cryo_db version
      - uses: actions/checkout@v3
      - run: |
          date > cryo_db/test.csv
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add cryo_db/test.csv
          git commit -m "Updated test.csv"
          git push
      